CREATE TABLE Payments (
    ReceiptId INT PRIMARY KEY IDENTITY(1000,1),
    StudentId NVARCHAR(50) NOT NULL,
    AmountPaid DECIMAL(18,2) NOT NULL,
    PaymentMethod NVARCHAR(50) NOT NULL,
    PaymentDate DATETIME NOT NULL DEFAULT GETDATE(),
    ProcessedBy NVARCHAR(50) NOT NULL
);
